site_name: 凌六の博客

# nav:
# 这部分是自定义导航页用的，目前懒得写
#   - Home: index.md
#   - CTF:
#     - BMP 位图详解: CTF\BMP 位图详解.md

# markdown_extensions:
  # - toc:
    # baselevel: 0
      # permalink: "#" # 给每个标题右边加上个永久链接

theme:
  name: material
  # custom_dir: overrides

  locale: zh_CN
  highlightjs: True
  hljs_languages:
    - python

site_url: https://zero6six.github.io/

extra_css:
  - custom/style.css
  
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
  - custom/myCustom.js

  - custom/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

markdown_extensions:
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: True

plugins:
  - mermaid2
  - search
  - callouts
  - autorefs